# Generated by Django 4.2 on 2025-08-27 17:05

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('aoi_geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('layer_flags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dono', models.ForeignKey(limit_choices_to={'role': 'dono'}, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_dono', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overlay_id', models.CharField(max_length=200)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('color', models.CharField(blank=True, max_length=16, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('geom_simpl', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features_criadas', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='projetos.project')),
            ],
        ),
        migrations.CreateModel(
            name='MapArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('export', 'Export final'), ('overlay_src', 'Overlay fonte'), ('aoi_src', 'AOI fonte'), ('outro', 'Outro')], default='export', max_length=20)),
                ('file', models.FileField(upload_to='projetos/%Y/%m/%d/')),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='projetos.project')),
            ],
        ),
        migrations.CreateModel(
            name='ExportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aoi_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('layer_flags', models.JSONField(default=dict)),
                ('overlays_used', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot', to='projetos.mapartifact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports_criados', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='projetos.project')),
            ],
        ),
        migrations.AddIndex(
            model_name='projectfeature',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geom'], name='projetos_pr_geom_2a4db1_gist'),
        ),
        migrations.AddIndex(
            model_name='projectfeature',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geom_simpl'], name='projetos_pr_geom_si_8fca99_gist'),
        ),
        migrations.AddIndex(
            model_name='projectfeature',
            index=models.Index(fields=['overlay_id'], name='projetos_pr_overlay_47671e_idx'),
        ),
    ]
