# Generated by Django 4.2 on 2025-11-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='municipio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
