# Generated by Django 4.2 on 2025-08-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rios', '0002_alter_waterway_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterway',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
