# Generated by Django 4.2 on 2025-08-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rios', '0003_alter_waterway_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterway',
            name='name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddIndex(
            model_name='waterway',
            index=models.Index(fields=['uf', 'name'], name='waterway_uf_name_idx'),
        ),
        migrations.AlterModelTable(
            name='waterway',
            table=None,
        ),
    ]
