# Generated by Django 4.2 on 2025-08-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rios', '0004_alter_waterway_name_waterway_waterway_uf_name_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterway',
            options={'verbose_name': 'Rio', 'verbose_name_plural': 'Rios'},
        ),
        migrations.RemoveIndex(
            model_name='waterway',
            name='waterway_uf_name_idx',
        ),
        migrations.RemoveField(
            model_name='waterway',
            name='uf',
        ),
        migrations.AddField(
            model_name='waterway',
            name='source',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='waterway',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='waterway',
            index=models.Index(fields=['name'], name='rios_waterw_name_931e4f_idx'),
        ),
    ]
