# Generated by Django 4.2 on 2025-10-03 12:02

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restricoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restricoes',
            name='area_loteavel',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4674),
        ),
        migrations.AlterField(
            model_name='areaverdev',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='corteareaverdev',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='margemferroviav',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='margemltv',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='margemriov',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='restricoes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ruav',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='areaverdev',
            index=models.Index(fields=['restricoes'], name='restricoes__restric_5960cd_idx'),
        ),
        migrations.AddIndex(
            model_name='areaverdev',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geom'], name='restricoes__geom_b85e96_gist'),
        ),
        migrations.AddIndex(
            model_name='corteareaverdev',
            index=models.Index(fields=['restricoes'], name='restricoes__restric_233172_idx'),
        ),
        migrations.AddIndex(
            model_name='corteareaverdev',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geom'], name='restricoes__geom_2bbb62_gist'),
        ),
        migrations.AddIndex(
            model_name='margemferroviav',
            index=models.Index(fields=['restricoes'], name='restricoes__restric_c17a59_idx'),
        ),
        migrations.AddIndex(
            model_name='margemferroviav',
            index=django.contrib.postgres.indexes.GistIndex(fields=['centerline'], name='restricoes__centerl_41c968_gist'),
        ),
        migrations.AddIndex(
            model_name='margemferroviav',
            index=django.contrib.postgres.indexes.GistIndex(fields=['faixa'], name='restricoes__faixa_100f6c_gist'),
        ),
        migrations.AddIndex(
            model_name='margemltv',
            index=models.Index(fields=['restricoes'], name='restricoes__restric_0e7e13_idx'),
        ),
        migrations.AddIndex(
            model_name='margemltv',
            index=django.contrib.postgres.indexes.GistIndex(fields=['centerline'], name='restricoes__centerl_3758c5_gist'),
        ),
        migrations.AddIndex(
            model_name='margemltv',
            index=django.contrib.postgres.indexes.GistIndex(fields=['faixa'], name='restricoes__faixa_6dcbc0_gist'),
        ),
        migrations.AddIndex(
            model_name='margemriov',
            index=models.Index(fields=['restricoes'], name='restricoes__restric_719665_idx'),
        ),
        migrations.AddIndex(
            model_name='margemriov',
            index=django.contrib.postgres.indexes.GistIndex(fields=['centerline'], name='restricoes__centerl_a0b188_gist'),
        ),
        migrations.AddIndex(
            model_name='margemriov',
            index=django.contrib.postgres.indexes.GistIndex(fields=['faixa'], name='restricoes__faixa_abb402_gist'),
        ),
        migrations.AddIndex(
            model_name='ruav',
            index=models.Index(fields=['restricoes'], name='restricoes__restric_28d3a2_idx'),
        ),
        migrations.AddIndex(
            model_name='ruav',
            index=django.contrib.postgres.indexes.GistIndex(fields=['eixo'], name='restricoes__eixo_21332f_gist'),
        ),
        migrations.AddIndex(
            model_name='ruav',
            index=django.contrib.postgres.indexes.GistIndex(fields=['mask'], name='restricoes__mask_a85d36_gist'),
        ),
    ]
