# Generated by Django 4.2 on 2025-10-07 13:15

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restricoes', '0002_restricoes_area_loteavel_alter_areaverdev_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualRestricaoV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4674)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restricoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricoes_manuais', to='restricoes.restricoes')),
            ],
        ),
        migrations.AddIndex(
            model_name='manualrestricaov',
            index=models.Index(fields=['restricoes'], name='restricoes__restric_9113b8_idx'),
        ),
        migrations.AddIndex(
            model_name='manualrestricaov',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geom'], name='restricoes__geom_4424b0_gist'),
        ),
    ]
