# Generated by Django 4.2 on 2025-12-17 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_project_municipio'),
        ('restricoes', '0003_manualrestricaov_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restricoes',
            name='is_oficial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restricoes',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricoes', to='projetos.project'),
        ),
        migrations.AlterField(
            model_name='restricoes',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
