# Generated by Django 4.2 on 2025-08-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0002_malhaferoviaria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MalhaFeroviaria',
            new_name='MalhaFerroviaria',
        ),
    ]
