# Generated by Django 4.2 on 2025-08-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0003_rename_malhaferoviaria_malhaferroviaria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='malhaferroviaria',
            options={'managed': False},
        ),
    ]
