# Generated by Django 4.2 on 2025-08-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0004_alter_malhaferroviaria_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='malhaferroviaria',
            table='geodata_malha_ferroviaria',
        ),
    ]
