# Generated by Django 4.2 on 2025-10-09 12:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelamentoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Plano padrão', max_length=160)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('frente_min_m', models.DecimalField(decimal_places=2, default=10, max_digits=8)),
                ('prof_min_m', models.DecimalField(decimal_places=2, default=25, max_digits=8)),
                ('larg_rua_vert_m', models.DecimalField(decimal_places=2, default=12, max_digits=8)),
                ('larg_rua_horiz_m', models.DecimalField(decimal_places=2, default=12, max_digits=8)),
                ('compr_max_quarteirao_m', models.DecimalField(decimal_places=2, default=200, max_digits=8)),
                ('orientacao_graus', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('srid_calc', models.IntegerField(default=3857)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelamento_planos', to='projetos.project')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelamentoVersao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_oficial', models.BooleanField(default=False)),
                ('nota', models.TextField(blank=True, default='')),
                ('frente_min_m', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prof_min_m', models.DecimalField(decimal_places=2, max_digits=8)),
                ('larg_rua_vert_m', models.DecimalField(decimal_places=2, max_digits=8)),
                ('larg_rua_horiz_m', models.DecimalField(decimal_places=2, max_digits=8)),
                ('compr_max_quarteirao_m', models.DecimalField(decimal_places=2, max_digits=8)),
                ('orientacao_graus', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('srid_calc', models.IntegerField(default=3857)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='parcelamento.parcelamentoplano')),
            ],
        ),
        migrations.CreateModel(
            name='Via',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('largura_m', models.DecimalField(decimal_places=2, default=12, max_digits=8)),
                ('tipo', models.CharField(choices=[('vertical', 'vertical'), ('horizontal', 'horizontal'), ('travessa', 'travessa'), ('acesso', 'acesso')], default='vertical', max_length=20)),
                ('nome', models.CharField(blank=True, default='', max_length=80)),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vias', to='parcelamento.parcelamentoversao')),
            ],
        ),
        migrations.CreateModel(
            name='Quarteirao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarteiroes', to='parcelamento.parcelamentoversao')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('area_m2', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('frente_m', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prof_media_m', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('orientacao_graus', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('score_qualidade', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('frente_min_m', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prof_min_m', models.DecimalField(decimal_places=2, max_digits=8)),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='parcelamento.parcelamentoversao')),
            ],
        ),
    ]
