# Generated by Django 4.2 on 2025-10-20 12:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcelamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calcada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('largura_m', models.DecimalField(decimal_places=2, default=2.5, max_digits=8)),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calcadas', to='parcelamento.parcelamentoversao')),
            ],
        ),
    ]
