# Generated by Django 4.2 on 2025-11-18 16:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcelamento', '0002_calcada'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='numero',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lote',
            name='quadra',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='via',
            name='categoria',
            field=models.CharField(choices=[('local', 'Local'), ('coletora', 'Coletora'), ('arterial', 'Arterial'), ('expressa', 'Expressa')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='via',
            name='is_ponte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='via',
            name='ponte_sobre',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.CreateModel(
            name='AreaPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('tipo', models.CharField(choices=[('praca', 'Praça'), ('esporte', 'Esporte / Lazer'), ('institucional', 'Institucional'), ('equipamento', 'Equipamento público'), ('outro', 'Outro')], default='praca', max_length=40)),
                ('nome', models.CharField(blank=True, default='', max_length=160)),
                ('descricao', models.TextField(blank=True, default='')),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_publicas', to='parcelamento.parcelamentoversao')),
            ],
        ),
    ]
