# Generated by Django 4.2 on 2025-11-18 17:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parcelamento', '0003_lote_numero_lote_quadra_via_categoria_via_is_ponte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areapublica',
            name='created_by_ia',
            field=models.BooleanField(default=False, help_text='Marcado como verdadeiro quando criado a partir de comando da IA'),
        ),
        migrations.AddField(
            model_name='areapublica',
            name='edited_manualmente',
            field=models.BooleanField(default=False, help_text='Verdadeiro se o usuário já editou este componente manualmente'),
        ),
        migrations.AddField(
            model_name='areapublica',
            name='ia_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata livre para IA (comandos, contexto, tags, etc.)'),
        ),
        migrations.AddField(
            model_name='areapublica',
            name='locked',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, o componente não é alterado por operações automáticas'),
        ),
        migrations.AddField(
            model_name='areapublica',
            name='origem',
            field=models.CharField(choices=[('heuristica', 'Gerado por heurística (backend)'), ('ia', 'Gerado por IA'), ('manual', 'Desenhado / editado manualmente'), ('importado', 'Importado de fonte externa')], default='heuristica', help_text='Origem do componente (heurística, IA, manual...)', max_length=20),
        ),
        migrations.AddField(
            model_name='areapublica',
            name='stable_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador estável para referência pela IA'),
        ),
        migrations.AddField(
            model_name='calcada',
            name='created_by_ia',
            field=models.BooleanField(default=False, help_text='Marcado como verdadeiro quando criado a partir de comando da IA'),
        ),
        migrations.AddField(
            model_name='calcada',
            name='edited_manualmente',
            field=models.BooleanField(default=False, help_text='Verdadeiro se o usuário já editou este componente manualmente'),
        ),
        migrations.AddField(
            model_name='calcada',
            name='ia_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata livre para IA (comandos, contexto, tags, etc.)'),
        ),
        migrations.AddField(
            model_name='calcada',
            name='locked',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, o componente não é alterado por operações automáticas'),
        ),
        migrations.AddField(
            model_name='calcada',
            name='origem',
            field=models.CharField(choices=[('heuristica', 'Gerado por heurística (backend)'), ('ia', 'Gerado por IA'), ('manual', 'Desenhado / editado manualmente'), ('importado', 'Importado de fonte externa')], default='heuristica', help_text='Origem do componente (heurística, IA, manual...)', max_length=20),
        ),
        migrations.AddField(
            model_name='calcada',
            name='stable_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador estável para referência pela IA'),
        ),
        migrations.AddField(
            model_name='lote',
            name='created_by_ia',
            field=models.BooleanField(default=False, help_text='Marcado como verdadeiro quando criado a partir de comando da IA'),
        ),
        migrations.AddField(
            model_name='lote',
            name='edited_manualmente',
            field=models.BooleanField(default=False, help_text='Verdadeiro se o usuário já editou este componente manualmente'),
        ),
        migrations.AddField(
            model_name='lote',
            name='ia_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata livre para IA (comandos, contexto, tags, etc.)'),
        ),
        migrations.AddField(
            model_name='lote',
            name='locked',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, o componente não é alterado por operações automáticas'),
        ),
        migrations.AddField(
            model_name='lote',
            name='origem',
            field=models.CharField(choices=[('heuristica', 'Gerado por heurística (backend)'), ('ia', 'Gerado por IA'), ('manual', 'Desenhado / editado manualmente'), ('importado', 'Importado de fonte externa')], default='heuristica', help_text='Origem do componente (heurística, IA, manual...)', max_length=20),
        ),
        migrations.AddField(
            model_name='lote',
            name='stable_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador estável para referência pela IA'),
        ),
        migrations.AddField(
            model_name='parcelamentoplano',
            name='created_by_ia',
            field=models.BooleanField(default=False, help_text='Marcado como verdadeiro quando criado a partir de comando da IA'),
        ),
        migrations.AddField(
            model_name='parcelamentoplano',
            name='edited_manualmente',
            field=models.BooleanField(default=False, help_text='Verdadeiro se o usuário já editou este componente manualmente'),
        ),
        migrations.AddField(
            model_name='parcelamentoplano',
            name='ia_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata livre para IA (comandos, contexto, tags, etc.)'),
        ),
        migrations.AddField(
            model_name='parcelamentoplano',
            name='ia_resumo',
            field=models.TextField(blank=True, default='', help_text='Resumo em linguagem natural das intenções do plano para a IA'),
        ),
        migrations.AddField(
            model_name='parcelamentoplano',
            name='locked',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, o componente não é alterado por operações automáticas'),
        ),
        migrations.AddField(
            model_name='parcelamentoplano',
            name='origem',
            field=models.CharField(choices=[('heuristica', 'Gerado por heurística (backend)'), ('ia', 'Gerado por IA'), ('manual', 'Desenhado / editado manualmente'), ('importado', 'Importado de fonte externa')], default='heuristica', help_text='Origem do componente (heurística, IA, manual...)', max_length=20),
        ),
        migrations.AddField(
            model_name='parcelamentoplano',
            name='stable_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador estável para referência pela IA'),
        ),
        migrations.AddField(
            model_name='parcelamentoversao',
            name='created_by_ia',
            field=models.BooleanField(default=False, help_text='Marcado como verdadeiro quando criado a partir de comando da IA'),
        ),
        migrations.AddField(
            model_name='parcelamentoversao',
            name='edited_manualmente',
            field=models.BooleanField(default=False, help_text='Verdadeiro se o usuário já editou este componente manualmente'),
        ),
        migrations.AddField(
            model_name='parcelamentoversao',
            name='ia_comando_gerador',
            field=models.TextField(blank=True, default='', help_text='Comando ou descrição em linguagem natural usado para gerar esta versão'),
        ),
        migrations.AddField(
            model_name='parcelamentoversao',
            name='ia_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata livre para IA (comandos, contexto, tags, etc.)'),
        ),
        migrations.AddField(
            model_name='parcelamentoversao',
            name='locked',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, o componente não é alterado por operações automáticas'),
        ),
        migrations.AddField(
            model_name='parcelamentoversao',
            name='origem',
            field=models.CharField(choices=[('heuristica', 'Gerado por heurística (backend)'), ('ia', 'Gerado por IA'), ('manual', 'Desenhado / editado manualmente'), ('importado', 'Importado de fonte externa')], default='heuristica', help_text='Origem do componente (heurística, IA, manual...)', max_length=20),
        ),
        migrations.AddField(
            model_name='parcelamentoversao',
            name='stable_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador estável para referência pela IA'),
        ),
        migrations.AddField(
            model_name='quarteirao',
            name='created_by_ia',
            field=models.BooleanField(default=False, help_text='Marcado como verdadeiro quando criado a partir de comando da IA'),
        ),
        migrations.AddField(
            model_name='quarteirao',
            name='edited_manualmente',
            field=models.BooleanField(default=False, help_text='Verdadeiro se o usuário já editou este componente manualmente'),
        ),
        migrations.AddField(
            model_name='quarteirao',
            name='ia_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata livre para IA (comandos, contexto, tags, etc.)'),
        ),
        migrations.AddField(
            model_name='quarteirao',
            name='locked',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, o componente não é alterado por operações automáticas'),
        ),
        migrations.AddField(
            model_name='quarteirao',
            name='origem',
            field=models.CharField(choices=[('heuristica', 'Gerado por heurística (backend)'), ('ia', 'Gerado por IA'), ('manual', 'Desenhado / editado manualmente'), ('importado', 'Importado de fonte externa')], default='heuristica', help_text='Origem do componente (heurística, IA, manual...)', max_length=20),
        ),
        migrations.AddField(
            model_name='quarteirao',
            name='stable_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador estável para referência pela IA'),
        ),
        migrations.AddField(
            model_name='via',
            name='created_by_ia',
            field=models.BooleanField(default=False, help_text='Marcado como verdadeiro quando criado a partir de comando da IA'),
        ),
        migrations.AddField(
            model_name='via',
            name='edited_manualmente',
            field=models.BooleanField(default=False, help_text='Verdadeiro se o usuário já editou este componente manualmente'),
        ),
        migrations.AddField(
            model_name='via',
            name='ia_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata livre para IA (comandos, contexto, tags, etc.)'),
        ),
        migrations.AddField(
            model_name='via',
            name='locked',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, o componente não é alterado por operações automáticas'),
        ),
        migrations.AddField(
            model_name='via',
            name='origem',
            field=models.CharField(choices=[('heuristica', 'Gerado por heurística (backend)'), ('ia', 'Gerado por IA'), ('manual', 'Desenhado / editado manualmente'), ('importado', 'Importado de fonte externa')], default='heuristica', help_text='Origem do componente (heurística, IA, manual...)', max_length=20),
        ),
        migrations.AddField(
            model_name='via',
            name='stable_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador estável para referência pela IA'),
        ),
    ]
