# Generated by Django 4.2 on 2025-12-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelamento', '0004_areapublica_created_by_ia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelamentoplano',
            name='direcao_quarteiroes',
            field=models.CharField(choices=[('auto_maior_lado', 'Automático (maior lado da área loteável)'), ('usar_orientacao_graus', 'Usar orientação fixa em graus')], default='auto_maior_lado', help_text='Define como orientar quarteirões: automático (maior lado da AL) ou usar um ângulo fixo (orientacao_graus).', max_length=32),
        ),
        migrations.AddField(
            model_name='parcelamentoplano',
            name='lado_ref_quarteiroes',
            field=models.CharField(choices=[('topo', 'Lado superior da área loteável'), ('base', 'Lado inferior'), ('esquerda', 'Lado esquerdo'), ('direita', 'Lado direito')], default='topo', help_text="Lado de referência da AL para calcular o ângulo. Por padrão, segue o ângulo da parte superior ('topo').", max_length=16),
        ),
    ]
