# Generated by Django 4.2 on 2025-12-17 12:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_project_municipio'),
        ('parcelamento', '0005_parcelamentoplano_direcao_quarteiroes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelamentoversao',
            name='calcada_encosta_aoi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcelamentoversao',
            name='calcada_largura_m',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=8),
        ),
        migrations.AddField(
            model_name='parcelamentoversao',
            name='cursor_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='parcelamentoversao',
            name='debug_last',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='parcelamentoversao',
            name='fileiras',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='parcelamentoversao',
            name='label',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='parcelamentoversao',
            name='linha_base',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='parcelamentoversao',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Versão pai (para opções A/B/C).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='parcelamento.parcelamentoversao'),
        ),
        migrations.AddField(
            model_name='parcelamentoversao',
            name='preferencia_cardinal',
            field=models.CharField(default='NW', help_text="Preferência cardinal, ex: 'NW' (Norte/Oeste).", max_length=4),
        ),
        migrations.AddField(
            model_name='parcelamentoversao',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelamento_versoes', to='projetos.project'),
        ),
        migrations.AddField(
            model_name='parcelamentoversao',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('candidate', 'candidate'), ('final', 'final')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='parcelamentoversao',
            name='step_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parcelamentoversao',
            name='ia_comando_gerador',
            field=models.TextField(blank=True, default='', help_text='Comando/descrição usado para gerar esta versão'),
        ),
        migrations.AlterField(
            model_name='parcelamentoversao',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versoes', to='parcelamento.parcelamentoplano'),
        ),
    ]
