# Generated by Django 4.2 on 2025-12-17
from django.db import migrations


def forwards_fill_project(apps, schema_editor):
    ParcelamentoVersao = apps.get_model("parcelamento", "ParcelamentoVersao")

    # Preenche project a partir de plano.project para todas as versões antigas
    qs = (
        ParcelamentoVersao.objects
        .filter(project__isnull=True, plano__isnull=False)
        .select_related("plano__project")
    )

    updated = 0
    for v in qs.iterator(chunk_size=1000):
        # plano.project sempre existia (plano tem FK obrigatória para projetos.Project)
        proj_id = getattr(v.plano, "project_id", None)
        if proj_id:
            v.project_id = proj_id
            v.save(update_fields=["project"])
            updated += 1

    # Segurança: se sobrar alguma versão sem project, melhor deixar explícito
    remaining = ParcelamentoVersao.objects.filter(project__isnull=True).count()
    if remaining:
        # Para não quebrar o migrate agora, a gente NÃO levanta exception.
        # Você vai checar isso e decidir o que fazer antes de tornar NOT NULL.
        # (Se quiser travar já aqui, me peça que eu mudo para raise.)
        pass


def backwards_unfill_project(apps, schema_editor):
    ParcelamentoVersao = apps.get_model("parcelamento", "ParcelamentoVersao")
    ParcelamentoVersao.objects.update(project=None)


class Migration(migrations.Migration):

    dependencies = [
        ("parcelamento", "0006_parcelamentoversao_calcada_encosta_aoi_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards_fill_project, backwards_unfill_project),
    ]
