# Generated by Django 4.2 on 2025-12-17
import django.db.models.deletion
from django.db import migrations, models


def assert_no_null_projects(apps, schema_editor):
    ParcelamentoVersao = apps.get_model("parcelamento", "ParcelamentoVersao")
    n = ParcelamentoVersao.objects.filter(project__isnull=True).count()
    if n:
        raise RuntimeError(
            f"Abortando: ainda existem {n} ParcelamentoVersao com project NULL. "
            "Rode o backfill/ajuste manual antes de tornar NOT NULL."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("parcelamento", "0007_backfill_parcelamentoversao_project"),
    ]

    operations = [
        migrations.RunPython(assert_no_null_projects,
                             migrations.RunPython.noop),
        migrations.AlterField(
            model_name="parcelamentoversao",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcelamento_versoes",
                to="projetos.project",
            ),
        ),
    ]
