# Generated by Django 4.2 on 2025-12-17 17:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restricoes', '0004_restricoes_is_oficial_alter_restricoes_project_and_more'),
        ('parcelamento', '0008_alter_parcelamentoversao_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelamentoversao',
            name='area_loteavel_snapshot',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4674),
        ),
        migrations.AddField(
            model_name='parcelamentoversao',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelamentoversao',
            name='restricoes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelamentos', to='restricoes.restricoes'),
        ),
        migrations.AddConstraint(
            model_name='parcelamentoversao',
            constraint=models.UniqueConstraint(condition=models.Q(('numero__isnull', False)), fields=('project', 'numero'), name='uniq_parcelamento_versao_numero_por_project'),
        ),
    ]
