# Generated by Django 4.2 on 2026-01-07 12:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parcelamento', '0009_parcelamentoversao_area_loteavel_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcada',
            name='via',
            field=models.ForeignKey(blank=True, help_text='Via à qual esta calçada pertence (lado esq/dir vai em ia_metadata/properties).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calcadas', to='parcelamento.via'),
        ),
        migrations.CreateModel(
            name='AreaVazia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador estável para referência pela IA')),
                ('origem', models.CharField(choices=[('heuristica', 'Gerado por heurística (backend)'), ('ia', 'Gerado por IA'), ('manual', 'Desenhado / editado manualmente'), ('importado', 'Importado de fonte externa')], default='heuristica', help_text='Origem do componente (heurística, IA, manual...)', max_length=20)),
                ('created_by_ia', models.BooleanField(default=False, help_text='Marcado como verdadeiro quando criado a partir de comando da IA')),
                ('edited_manualmente', models.BooleanField(default=False, help_text='Verdadeiro se o usuário já editou este componente manualmente')),
                ('locked', models.BooleanField(default=False, help_text='Se verdadeiro, o componente não é alterado por operações automáticas')),
                ('ia_metadata', models.JSONField(blank=True, default=dict, help_text='Metadata livre para IA (comandos, contexto, tags, etc.)')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('motivo', models.CharField(blank=True, default='', max_length=80)),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_vazias', to='parcelamento.parcelamentoversao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
